"""Tests for secret_scan module — unit tests with mocked container.

No committed file may contain a literal secret-shaped string (#676 trap 1).
Fixture values are built at runtime from parts.
"""

from __future__ import annotations

import json
import os
from unittest.mock import MagicMock, patch

import pytest

from sunaba.tools.secret_scan import (  # noqa: I001, F401
    _OVERRIDE_LOCK,
    _OVERRIDE_MAP,
    _baseline_enabled,
    _check_detect_secrets,
    _update_baseline,
    check_override,
    consume_override,
    exec_in_container,
    run_secret_scan,
    secret_scan_override,
)

# ============================================================================
# Helpers: build safe fixture data at runtime
# ============================================================================


def _dummy_version_output() -> str:
    """Return fake detect-secrets version output — matches real tool output."""
    return "1.5.0"


def _make_clean_scan_json() -> str:
    """Return JSON with no findings (empty results dict)."""
    return json.dumps({
        "generated_at": "2026-07-20T00:00:00Z",
        "plugins_used": [],
        "results": {},
    })


def _make_finding_json(filename: str, line: int, secret_type: str) -> str:
    """Build detect-secrets JSON output with one finding.

    Matches the REAL output shape from detect-secrets: no ``is_secret``
    key (detect-secrets does not emit that — it is only written by
    ``detect-secrets audit``, a manual triage step).

    The ``hashed_secret`` is a synthetic SHA-256 hex string built at
    runtime so the committed file contains no actual secret hash.
    """
    import hashlib
    fake_secret = "".join(
        chr(ord(c) + 1) for c in "no-real-secret-here"
    )
    hashed = hashlib.sha256(fake_secret.encode()).hexdigest()
    return json.dumps({
        "generated_at": "2026-07-20T00:00:00Z",
        "plugins_used": [{"name": "AWSKeyDetector"}],
        "results": {
            filename: [
                {
                    "type": secret_type,
                    "filename": filename,
                    "line_number": line,
                    "hashed_secret": hashed,
                    "is_verified": False,
                }
            ]
        },
    })


def _load_real_scan_fixture() -> str:
    """Load genuine detect-secrets scan output from the committed fixture.

    The fixture was generated by running::

        detect-secrets scan real_secret_input.py

    on a file containing a secret-shaped value.  This exercises the parser
    with the actual shape the tool produces (no ``is_secret`` key, etc.).
    """
    import pathlib
    fixture_path = pathlib.Path(__file__).parent / "fixtures" / "secret_scan_real_output.json"
    return fixture_path.read_text()


# ============================================================================
# Fake container with scriptable exec_run
# ============================================================================

# ExecResult is a namedtuple (exit_code, output) returned by container.exec_run.
# Defined inline here so the test module does not depend on docker at import time.
_ExecResult = __import__("collections").namedtuple("ExecResult", ("exit_code", "output"))


def _make_container(
    exec_results: list[tuple[int, str, str]],
) -> MagicMock:
    """Build a mock container where successive exec_run calls return
    scripted (exit_code, stdout, stderr).

    Each exec_run call on the returned mock returns an ``ExecResult``
    namedtuple whose ``.output`` is ``(stdout_bytes, stderr_bytes)``
    (the demux=True shape).
    """
    container = MagicMock()
    results: list[_ExecResult] = []

    for ec, stdout, stderr in exec_results:
        stdout_bytes = stdout.encode("utf-8")
        stderr_bytes = stderr.encode("utf-8")
        results.append(_ExecResult(ec, (stdout_bytes, stderr_bytes)))

    container.exec_run.side_effect = results

    return container


# ============================================================================
# _check_detect_secrets
# ============================================================================


class TestCheckDetectSecrets:
    """_check_detect_secrets probes for the detect-secrets binary."""

    def test_available(self) -> None:
        """Version output with 'detect_secrets' → available."""
        container = _make_container([(0, _dummy_version_output(), "")])
        assert _check_detect_secrets(container) is True

    def test_not_available(self) -> None:
        """Non-zero exit → not available."""
        container = _make_container([(1, "", "command not found")])
        assert _check_detect_secrets(container) is False

    def test_empty_output(self) -> None:
        """Zero exit but empty output → not available."""
        container = _make_container([(0, "", "")])
        assert _check_detect_secrets(container) is False


# ============================================================================
# run_secret_scan
# ============================================================================


class TestRunSecretScan:
    """run_secret_scan: the core scanning logic."""

    def test_no_files(self) -> None:
        """Empty file list → clean, no scan attempted."""
        container = _make_container([])
        result = run_secret_scan(container, [], "/tmp/repo")
        assert result["secret_scan"] == "clean"
        assert result["files_scanned"] == []

    def test_detect_secrets_unavailable(self) -> None:
        """detect-secrets missing → prominent skip, no block."""
        container = _make_container([(1, "", "not found")])
        result = run_secret_scan(container, ["file.py"], "/tmp/repo")
        assert "SKIPPED" in result["secret_scan"]
        assert "detect-secrets unavailable" in result["secret_scan"]

    def test_clean_scan(self) -> None:
        """detect-secrets returns empty results → clean.

        The new code path never does a ``test -f`` before the scan
        (no ``--baseline`` flag).  After the scan it tries to ``cat``
        the baseline file;  baseline OFF means we skip that step.
        """
        container = _make_container([
            (0, _dummy_version_output(), ""),       # check available
            (0, _make_clean_scan_json(), ""),         # scan output
        ])
        with patch(
            "sunaba.tools.secret_scan._baseline_enabled",
            return_value=False,
        ):
            result = run_secret_scan(container, ["file.py"], "/tmp/repo")
        assert result["secret_scan"] == "clean"
        assert result["files_scanned"] == ["file.py"]

    def test_findings_detected(self) -> None:
        """Scan with a finding — returns findings with file/line/type.

        This test uses mock data WITHOUT ``is_secret``, matching the real
        detect-secrets output shape.  If someone re-adds the ``is_secret``
        filter (Bug 1), this test will go red — the finding is present but
        would be silently dropped.
        """
        container = _make_container([
            (0, _dummy_version_output(), ""),       # check available
            (0, _make_finding_json("keys.py", 5, "AWS Secret Key"), ""),
        ])
        with patch(
            "sunaba.tools.secret_scan._baseline_enabled",
            return_value=False,
        ):
            result = run_secret_scan(container, ["keys.py"], "/tmp/repo")
        assert result["secret_scan"] == "findings"
        assert len(result["findings"]) == 1
        f = result["findings"][0]
        assert f["file"] == "keys.py"
        assert f["line"] == 5
        assert "AWS" in f["type"]

    def test_findings_detected_with_real_fixture(self) -> None:
        """Parser handles genuine detect-secrets output (no ``is_secret``)."""
        fixture_str = _load_real_scan_fixture()
        container = _make_container([
            (0, _dummy_version_output(), ""),
            (0, fixture_str, ""),
        ])
        with patch(
            "sunaba.tools.secret_scan._baseline_enabled",
            return_value=False,
        ):
            result = run_secret_scan(
                container, ["real_secret_input.py"], "/tmp/repo",
            )
        assert result["secret_scan"] == "findings"
        assert len(result["findings"]) >= 2

    def test_scan_failure(self) -> None:
        """detect-secrets crash → warning message, not a crash."""
        container = _make_container([
            (0, _dummy_version_output(), ""),
            (1, "", "segfault"),
        ])
        with patch(
            "sunaba.tools.secret_scan._baseline_enabled",
            return_value=False,
        ):
            result = run_secret_scan(container, ["bad.py"], "/tmp/repo")
        assert "WARNING" in result["secret_scan"]
        assert "failed" in result["secret_scan"]

    def test_unparseable_output_is_error_not_clean(self) -> None:
        """Scan that produces garbage output → error, never ``clean``.

        Bug 2 regression: unparseable output used to be reported as
        ``"clean"``, silently swallowing the scan failure.
        """
        container = _make_container([
            (0, _dummy_version_output(), ""),
            (0, "this is not json {{{", ""),
        ])
        with patch(
            "sunaba.tools.secret_scan._baseline_enabled",
            return_value=False,
        ):
            result = run_secret_scan(container, ["bad.py"], "/tmp/repo")
        assert result["secret_scan"] != "clean"
        assert "ERROR" in result["secret_scan"]
        assert "publish blocked" in result["secret_scan"]

    def test_empty_output_is_error_not_clean(self) -> None:
        """Scan that produces empty stdout → error, never ``clean``.

        Bug 2 regression: empty output (e.g. from ``--baseline`` mode)
        used to hit JSONDecodeError and was silently treated as clean.
        """
        container = _make_container([
            (0, _dummy_version_output(), ""),
            (0, "", ""),
        ])
        with patch(
            "sunaba.tools.secret_scan._baseline_enabled",
            return_value=False,
        ):
            result = run_secret_scan(container, ["bad.py"], "/tmp/repo")
        assert result["secret_scan"] != "clean"
        assert "ERROR" in result["secret_scan"]
        assert "empty output" in result["secret_scan"]

    def test_baseline_suppresses_known_finding(self) -> None:
        """A finding present in .secrets.baseline is NOT reported."""
        import hashlib
        fake_secret = "".join(
            chr(ord(c) + 1) for c in "known-secret"
        )
        known_hash = hashlib.sha256(fake_secret.encode()).hexdigest()
        # Baseline with the known finding
        baseline_json = json.dumps({
            "generated_at": "2026-01-01T00:00:00Z",
            "plugins_used": [],
            "results": {
                "safe.py": [
                    {
                        "type": "Secret Keyword",
                        "filename": "safe.py",
                        "line_number": 10,
                        "hashed_secret": known_hash,
                        "is_verified": False,
                    }
                ]
            },
        })
        # Scan output has the SAME finding (already in baseline)
        scan_json = json.dumps({
            "generated_at": "2026-07-20T00:00:00Z",
            "plugins_used": [],
            "results": {
                "safe.py": [
                    {
                        "type": "Secret Keyword",
                        "filename": "safe.py",
                        "line_number": 10,
                        "hashed_secret": known_hash,
                        "is_verified": False,
                    }
                ]
            },
        })
        # Scan output with a NEW finding (not in baseline)
        new_hash = hashlib.sha256(b"new-secret-value").hexdigest()
        scan_with_new_json = json.dumps({
            "generated_at": "2026-07-20T00:00:00Z",
            "plugins_used": [],
            "results": {
                "safe.py": [
                    {
                        "type": "Secret Keyword",
                        "filename": "safe.py",
                        "line_number": 10,
                        "hashed_secret": known_hash,
                        "is_verified": False,
                    },
                    {
                        "type": "Secret Keyword",
                        "filename": "new.py",
                        "line_number": 5,
                        "hashed_secret": new_hash,
                        "is_verified": False,
                    },
                ]
            },
        })

        # CASE 1: finding exists in baseline → suppressed
        container = _make_container([
            (0, _dummy_version_output(), ""),       # check available
            (0, scan_json, ""),                      # scan output
            (0, baseline_json, ""),                  # cat .secrets.baseline
        ])
        with patch(
            "sunaba.tools.secret_scan._baseline_enabled",
            return_value=True,
        ):
            result = run_secret_scan(
                container, ["safe.py"], "/tmp/repo",
            )
        assert result["secret_scan"] == "clean", (
            "Known finding in baseline should be suppressed"
        )

        # CASE 2: both known AND new finding → only new is reported
        container2 = _make_container([
            (0, _dummy_version_output(), ""),
            (0, scan_with_new_json, ""),
            (0, baseline_json, ""),                  # same baseline
        ])
        with patch(
            "sunaba.tools.secret_scan._baseline_enabled",
            return_value=True,
        ):
            result2 = run_secret_scan(
                container2, ["safe.py", "new.py"], "/tmp/repo",
            )
        assert result2["secret_scan"] == "findings"
        assert len(result2["findings"]) == 1
        assert result2["findings"][0]["hashed_secret"] == new_hash

    def test_baseline_absent_all_findings_reported(self) -> None:
        """When no baseline file exists, cat returns ec=1, all findings shown."""
        container = _make_container([
            (0, _dummy_version_output(), ""),
            (0, _make_finding_json("keys.py", 5, "AWS Secret Key"), ""),
            # cat .secrets.baseline → ec=1 (file not found)
            (1, "", "No such file"),
        ])
        with patch(
            "sunaba.tools.secret_scan._baseline_enabled",
            return_value=True,
        ):
            result = run_secret_scan(container, ["keys.py"], "/tmp/repo")
        assert result["secret_scan"] == "findings"
        assert len(result["findings"]) == 1


# ============================================================================
# End-to-end tests with the real detect-secrets binary
# ============================================================================


class TestRealDetectSecrets:
    """Drive the actual detect-secrets binary installed in this container.

    These tests verify that a file with a real secret-shaped value produces
    a blocking result when parsed through the same logic ``run_secret_scan``
    uses, confirming the fix for Bug 1 (``is_secret`` filter) and Bug 2
    (baseline/stdout handling).
    """

    @pytest.fixture(autouse=True)
    def _scratch_dir(self, tmp_path: object) -> None:
        self.scratch = tmp_path  # type: ignore[attr-defined]

    def _run_real_scan(self, file_path: str) -> dict:
        """Run detect-secrets on *file_path* and return parsed JSON.

        detect-secrets needs ``cwd`` to be the parent of the scanned file;
        otherwise it silently returns no findings.
        """
        import os
        import subprocess
        parent = os.path.dirname(os.path.abspath(file_path))
        result = subprocess.run(
            ["detect-secrets", "scan", file_path],
            capture_output=True, text=True, timeout=30,
            cwd=parent,
        )
        assert result.returncode == 0, f"detect-secrets failed: {result.stderr}"
        return json.loads(result.stdout)

    def test_real_secret_produces_findings(self) -> None:
        """A file with secret-shaped variable assignments → findings detected.

        detect-secrets KeywordDetector flags variable names containing
        ``secret`` when they appear in assignment contexts (e.g.
        ``SECRETS_BASELINE = "..."``, ``hashed_secret = "..."``).

        This test uses the ACTUAL detect-secrets binary and builds the
        file content at runtime (no committed literal secret).
        """
        secret_file = self.scratch / "secret_input.py"  # type: ignore[attr-defined]
        secret_file.write_text(
            'SECRETS_BASELINE_ENV = "SUNABA_SECRETS"\n'
            'secret_scan_result = "findings"\n'
            'hashed_secret = "abc123"\n'
        )
        scan_data = self._run_real_scan(str(secret_file))
        results: dict = scan_data.get("results", {})
        total_findings = sum(len(v) for v in results.values())
        assert total_findings >= 2, (
            f"Expected ≥2 findings, got {total_findings}: "
            f"{json.dumps(results, indent=2)}"
        )

    def test_real_secret_through_parse_logic(self) -> None:
        """Feed real detect-secrets output through the parser → findings.

        This tests that the parsing logic (which no longer uses
        ``is_secret``) correctly identifies findings from the real tool.
        """
        secret_file = self.scratch / "secret_parse_input.py"  # type: ignore[attr-defined]
        secret_file.write_text(
            'SECRETS_BASELINE_ENV = "SUNABA_SECRETS"\n'
            'secret_scan_result = "findings"\n'
            'hashed_secret = "abc123"\n'
        )
        scan_data = self._run_real_scan(str(secret_file))

        # Apply the SAME logic as run_secret_scan
        results: dict = scan_data.get("results", {})
        findings: list[dict] = []
        for filename, file_findings in results.items():
            for finding in file_findings:
                # NO is_secret filter (Bug 1 fix)
                findings.append({
                    "file": finding.get("filename", filename),
                    "line": finding.get("line_number", 0),
                    "type": finding.get("type", "unknown"),
                    "hashed_secret": finding.get("hashed_secret", ""),
                })

        assert len(findings) >= 2, (
            f"Expected ≥2 findings, got {len(findings)}. "
            "If Bug 1 (is_secret filter) is reintroduced, "
            "this test will be the canary."
        )


# ============================================================================
# _baseline_enabled
# ============================================================================


class TestBaselineEnabled:
    """SUNABA_SECRETS_BASELINE environment variable."""

    def test_default_enabled(self) -> None:
        """Unset -> enabled (default)."""
        with patch.dict(os.environ, {}, clear=True):
            assert _baseline_enabled() is True

    def test_explicit_true(self) -> None:
        with patch.dict(os.environ, {"SUNABA_SECRETS_BASELINE": "true"}):
            assert _baseline_enabled() is True

    def test_false(self) -> None:
        with patch.dict(os.environ, {"SUNABA_SECRETS_BASELINE": "false"}):
            assert _baseline_enabled() is False

    def test_zero(self) -> None:
        with patch.dict(os.environ, {"SUNABA_SECRETS_BASELINE": "0"}):
            assert _baseline_enabled() is False


# ============================================================================
# check_override
# ============================================================================


class TestCheckOverride:
    """One-time in-memory override (baseline OFF path).

    ``check_override`` peeks without consuming.  ``consume_override``
    pops the flag (called after a successful push).
    """

    def test_no_override(self) -> None:
        """No override set -> False."""
        _OVERRIDE_MAP.clear()
        assert check_override("cid123456789") is False
        assert consume_override("cid123456789") is False

    def test_override_peek_and_consume(self) -> None:
        """Peek returns True but does NOT consume; consume pops once."""
        _OVERRIDE_MAP.clear()
        cid = "abc123def456"
        with _OVERRIDE_LOCK:
            _OVERRIDE_MAP[cid] = True
        assert check_override(cid) is True    # peek
        assert check_override(cid) is True    # still there
        assert consume_override(cid) is True  # consumed
        assert check_override(cid) is False   # gone
        assert consume_override(cid) is False # already consumed

    def test_override_different_container(self) -> None:
        """Override for container A does not affect container B."""
        _OVERRIDE_MAP.clear()
        with _OVERRIDE_LOCK:
            _OVERRIDE_MAP["aaa"] = True
        assert check_override("aaa") is True
        assert check_override("bbb") is False
        assert consume_override("bbb") is False


# ============================================================================
# _update_baseline
# ============================================================================


class TestUpdateBaseline:
    """Updating .secrets.baseline (baseline ON path)."""

    def test_update_creates_baseline(self) -> None:
        """When no baseline exists, creates one with merged results."""
        container = _make_container([
            # cat .secrets.baseline -> ec=1 (not found)
            (1, "", "No such file"),
            # detect-secrets scan
            (0, _make_finding_json("secret.py", 3, "Private Key"), ""),
            # cat > .secrets.baseline (write)
            (0, "", ""),
        ])
        err = _update_baseline(container, ["secret.py"], "/tmp/repo")
        assert err is None

    def test_update_merge_existing(self) -> None:
        """When baseline exists, merges new results with old."""
        old_baseline = json.dumps({
            "generated_at": "2026-01-01T00:00:00Z",
            "plugins_used": [],
            "results": {"old.py": []},
        })
        container = _make_container([
            (0, old_baseline, ""),                    # cat existing
            (0, _make_finding_json("new.py", 1, "AWS Secret Key"), ""),
            (0, "", ""),                               # write
        ])
        err = _update_baseline(container, ["new.py"], "/tmp/repo")
        assert err is None

    def test_update_scan_fails(self) -> None:
        """When scan fails, returns error message."""
        container = _make_container([
            (1, "", "No such file"),
            (1, "", "detect-secrets crashed"),
        ])
        err = _update_baseline(container, ["bad.py"], "/tmp/repo")
        assert err is not None
        assert "failed" in err


# ============================================================================
# secret_scan_override (MCP tool — Docker-dependent via _docker())
# ============================================================================


class TestSecretScanOverride:
    """secret_scan_override MCP tool — tested via mocked container."""

    @pytest.fixture(autouse=True)
    def _clear_overrides(self) -> None:
        _OVERRIDE_MAP.clear()

    def test_container_not_found(self) -> None:
        """Unknown container_id → error message."""
        with patch("sunaba.tools.secret_scan._docker") as mock_docker:
            client = MagicMock()
            client.containers.get.side_effect = Exception("not found")
            mock_docker.return_value = client
            result = secret_scan_override("nonexistent1234")
            payload = json.loads(result)
            assert payload["status"] == "error"

    def test_baseline_off_sets_override(self) -> None:
        """Baseline OFF → in-memory override flag set."""
        container = _make_container([
            # detect-secrets --version
            (0, "detect_secrets-1.5.0\n", ""),
        ])

        client = MagicMock()
        client.containers.get.return_value = container

        with (
            patch("sunaba.tools.secret_scan._docker", return_value=client),
            patch(
                "sunaba.tools.secret_scan._baseline_enabled",
                return_value=False,
            ),
            patch("sunaba.tools.secret_scan.record_boundary_crossing"),
            patch("sunaba.tools.secret_scan.record_tool_use"),
        ):
            result = secret_scan_override(
                "testcid123456", working_dir="/workspace",
                files=["secret.py", "config.py"],
            )
            payload = json.loads(result)
            assert payload["status"] == "ok"
            assert payload["action"] == "override_set"
            # In-memory flag should be set (peek)
            assert check_override("testcid123456") is True
            # Peek is non-destructive — still there
            assert check_override("testcid123456") is True
            # consume_override consumes it
            assert consume_override("testcid123456") is True
            # Gone after consumption
            assert check_override("testcid123456") is False

    def test_no_detect_secrets_returns_error(self) -> None:
        """detect-secrets not available → error from override too."""
        container = _make_container([
            # detect-secrets --version fails
            (1, "", "command not found"),
        ])

        client = MagicMock()
        client.containers.get.return_value = container

        with (
            patch("sunaba.tools.secret_scan._docker", return_value=client),
            patch("sunaba.tools.secret_scan.record_tool_use"),
            patch("sunaba.tools.vcs.gitroot.resolve_git_root",
                  return_value="/workspace"),
        ):
            result = secret_scan_override(
                "testcid123456", working_dir="/workspace",
                files=["secret.py"],
            )
            payload = json.loads(result)
            assert payload["status"] == "error"
            assert "not available" in payload["error"]

# ============================================================================
# Regression: exec_in_container must use real Container API surface
# ============================================================================


class TestExecInContainerAPISurface:
    """Verify that exec_in_container only calls methods from the real
    ``docker.models.containers.Container`` class API (acceptance criterion 4).

    These tests use ``create_autospec(Container)`` rather than checking
    ``hasattr``, so that exec_in_container is actually exercised against a
    mock with the **exact** interface of the real class.  If it ever calls
    ``exec_create`` / ``exec_start`` / ``exec_inspect``, the autospec raises
    ``AttributeError`` — a MagicMock fabricating those attributes cannot
    make the test pass.
    """

    def test_exec_run_is_called_through_autospec(self) -> None:
        """exec_in_container calls exec_run on an autospec(Container)."""
        from unittest.mock import create_autospec

        from docker.models.containers import Container

        # autospec creates a mock that only has Container's real methods
        mock = create_autospec(Container, instance=True)
        mock.exec_run.return_value = _ExecResult(0, (b"1.5.0", b""))

        ec, out, err = exec_in_container(mock, ["detect-secrets", "--version"])

        assert ec == 0
        assert out == "1.5.0"
        assert err == ""
        mock.exec_run.assert_called_once_with(
            cmd=["detect-secrets", "--version"],
            stdout=True,
            stderr=True,
            workdir=None,
            demux=True,
        )

    def test_non_demux_fallback_is_exercised(self) -> None:
        """When exec_run(demux=True) raises TypeError, the fallback without
        demux is used.  This covers the non-demux fallback path (finding 3)."""
        from unittest.mock import create_autospec

        from docker.models.containers import Container

        mock = create_autospec(Container, instance=True)
        # First call (demux=True) raises TypeError
        # Second call (no demux) succeeds with multiplexed output
        mock.exec_run.side_effect = [
            TypeError("demux not supported"),
            _ExecResult(0, b"1.5.0"),
        ]

        ec, out, err = exec_in_container(mock, ["detect-secrets", "--version"])

        assert ec == 0
        assert out == "1.5.0"
        assert err == ""  # non-demux: all output is stdout
        assert mock.exec_run.call_count == 2
        # Second call had no demux keyword
        _, second_kwargs = mock.exec_run.call_args_list[1]
        assert "demux" not in second_kwargs

# ============================================================================
# --no-verify flag (issue #701)
# ============================================================================


class TestNoVerifyFlag:
    """The scan command must include ``--no-verify`` so that verification
    plugins (aws, cloudant, …) cannot make outbound calls.  Inside the
    sandbox the egress proxy blocks all such calls, and detect-secrets
    silently treats a non-200 as "not a secret", dropping findings.
    """

    @staticmethod
    def _scan_command_contains_no_verify(scan_calls, expected: bool) -> None:
        """Assert that at least one exec_run call contains --no-verify
        (or, when *expected* is False, that none do).  Searches ALL calls
        rather than hardcoding an index so the assertion survives
        refactoring that reorders or adds exec_run invocations."""
        matching = [
            c for c in scan_calls
            if isinstance(c.kwargs.get("cmd"), list)
            and "--no-verify" in " ".join(c.kwargs["cmd"])
        ]
        if expected:
            assert matching, (
                "No exec_run call contained --no-verify. "
                f"Calls: {[c.kwargs.get('cmd') for c in scan_calls]}"
            )
        else:
            assert not matching, (
                "Found --no-verify in exec_run call when it should be absent. "
                f"Calls: {[c.kwargs.get('cmd') for c in scan_calls]}"
            )

    def test_scan_command_includes_no_verify(self) -> None:
        """The detect-secrets scan command issued by run_secret_scan
        includes ``--no-verify``."""
        container = _make_container([
            (0, _dummy_version_output(), ""),        # --version check
            (0, _make_clean_scan_json(), ""),         # scan output
        ])
        with patch(
            "sunaba.tools.secret_scan._baseline_enabled",
            return_value=False,
        ):
            run_secret_scan(container, ["file.py"], "/tmp/repo")

        self._scan_command_contains_no_verify(
            container.exec_run.call_args_list, expected=True,
        )

    def test_baseline_update_includes_no_verify(self) -> None:
        """The detect-secrets scan command issued by _update_baseline
        also includes ``--no-verify``."""
        container = _make_container([
            # cat .secrets.baseline -> ec=1 (not found)
            (1, "", "No such file"),
            # detect-secrets scan
            (0, _make_clean_scan_json(), ""),
            # write baseline
            (0, "", ""),
        ])
        from sunaba.tools.secret_scan import _update_baseline
        _update_baseline(container, ["file.py"], "/tmp/repo")

        self._scan_command_contains_no_verify(
            container.exec_run.call_args_list, expected=True,
        )

# ============================================================================
# AWS key pair detection (issue #701 regression guard)
# ============================================================================


def _make_aws_key_pair_json(filename: str) -> str:
    """Build detect-secrets JSON output representing an AWS access key ID
    AND a secret access key in the same file — the scenario that was silently
    dropped before --no-verify.

    All values are constructed at runtime so no literal credentials are
    committed.
    """
    import hashlib

    # Build two distinct fake secrets
    fake_access_key = "".join(
        chr(ord(c) + 1) for c in "no-real-access-key"
    )
    fake_secret_key = "".join(
        chr(ord(c) + 2) for c in "no-real-secret-key"
    )
    hashed_access = hashlib.sha256(fake_access_key.encode()).hexdigest()
    hashed_secret = hashlib.sha256(fake_secret_key.encode()).hexdigest()

    return json.dumps({
        "generated_at": "2026-07-20T00:00:00Z",
        "plugins_used": [{"name": "AWSKeyDetector"}],
        "results": {
            filename: [
                {
                    "type": "AWS Secret Key",
                    "filename": filename,
                    "line_number": 5,
                    "hashed_secret": hashed_access,
                    "is_verified": False,
                },
                {
                    "type": "AWS Secret Key",
                    "filename": filename,
                    "line_number": 6,
                    "hashed_secret": hashed_secret,
                    "is_verified": False,
                },
            ]
        },
    })


class TestAWSKeyPairDetection:
    """An AWS access key combined with a secret key must produce a blocking
    result — the scenario that --no-verify fixes (issue #701)."""

    def test_aws_key_pair_findings_survive(self) -> None:
        """Two AWS findings (access key + secret key) both survive parsing."""
        container = _make_container([
            (0, _dummy_version_output(), ""),
            (0, _make_aws_key_pair_json("secrets.py"), ""),
        ])
        with patch(
            "sunaba.tools.secret_scan._baseline_enabled",
            return_value=False,
        ):
            result = run_secret_scan(
                container, ["secrets.py"], "/tmp/repo",
            )
        assert result["secret_scan"] == "findings", (
            f"AWS key pair should produce findings, got: {result['secret_scan']}"
        )
        assert len(result["findings"]) == 2, (
            f"Expected 2 AWS findings, got {len(result.get('findings', []))}"
        )
        for f in result["findings"]:
            assert "AWS" in f["type"]
            assert f["file"] == "secrets.py"
