"""Exec tools: sandbox_exec, sandbox_exec_background, sandbox_exec_check."""

from __future__ import annotations

import base64
import json
import os
import re
import shlex
import time
from typing import Annotated, Any

from docker.errors import NotFound
from pydantic import BeforeValidator

from sunaba import capture_health
from sunaba.edit_verify.shell import (
    _FOREGROUND_MARKER_ENV,
    ForegroundTreeTimeout,
    close_foreground_deadline,
    foreground_marker_environment,
    foreground_sweep_command,
    foreground_wait_fragment,
    new_foreground_marker,
    open_foreground_deadline,
    reap_foreground_tree,
    resolve_foreground_deadline,
    run_exec_under_foreground_deadline,
    subreaper_exec_command,
)
from sunaba.journal import record_exec as journal_record_exec
from sunaba.journal import record_exec_start as journal_record_exec_start
from sunaba.journal import record_tool_use
from sunaba.output_control import (
    build_output_envelope,
    compress_failures,
    compress_repeated_lines,
    content_withheld,
    count_lines,
    sanitize_output,
    truncate_by_tokens,
    truncate_output,
)
from sunaba.output_store import OUTPUT_STORE
from sunaba.tools.common import (
    RECOVERY_DOCKER_TIMEOUT,
    _coerce_list_arg,
    _docker,
    container_not_found_error,
)

# Job IDs are generated by sandbox_exec_background as
# "<container_id>-<epoch>[-<hex>]"; the trailing hex is the random
# component added in #829 so two jobs started in the same second on the
# same container cannot collide.  The pre-#829 form without the hex
# suffix is deliberately still accepted by sandbox_exec_check: a job
# started before an upgrade may legitimately be polled afterwards while
# still in flight.  The container_id part is the caller-supplied prefix
# (docker id prefix or name), kept as-is.
_JOB_ID_RE = re.compile(r"^[A-Za-z0-9_.-]+-[0-9]+(?:-[0-9a-f]+)?$")


# argv mode exists because shell quoting of git/gh bodies is a footgun
# (#234/#228); it bypasses /bin/bash -c entirely.
def sandbox_exec(
    container_id: str,
    commands: Annotated[list[str], BeforeValidator(_coerce_list_arg)] | None = None,
    working_dir: str = "",
    verbose: str = "summary",
    max_lines: int = 100,
    offset: int = 0,
    limit: int = 50,
    timeout: int = 0,
    max_output_tokens: int = 0,
    argv: Annotated[list[str], BeforeValidator(_coerce_list_arg)] | None = None,
) -> str:
    """Run commands in the repo root (/workspace); working_dir overrides it.
    commands are joined by && in one exec, preserving cwd/env.
    Raw newlines in commands break JSON-RPC: use escaped newlines, a script
    file, or argv (direct execution, no shell). Prefer dedicated read/edit/search
    tools and argv for git/gh to avoid shell quoting.

    Args:
        container_id: Container ID prefix.
        commands: Shell commands run sequentially. No raw newlines
            (see above).
        working_dir: cd here before running.
        verbose: 'error_only', 'summary', or 'full'.
        max_lines: Max lines shown in summary/error_only mode.
        offset: 0-indexed line offset for paging output.
        limit: Max lines per page.
        timeout: Kill after N seconds (0 = no limit); on expiry
            status='timeout', exit_code=124.
        max_output_tokens: Summarize output to this token budget (0 = off);
            omitted output is saved for read_output when within cache limits.
        argv: Direct exec, no shell -- quoting and embedded newlines
            pass through literally.  Mutually exclusive with commands.

    Returns:
        JSON: status, output, paging metadata; exit_code and stderr on
        failure.

        ``shown`` is the number of lines in the returned ``output``.
        ``total_lines`` is the line count of the whole output, in every
        mode.  ``truncated`` means "``output`` is not the whole output":
        it is true when content was withheld by summary truncation, by
        ``max_output_tokens``, by ``error_only`` hiding a successful
        run's output, or by paging -- including when ``offset`` > 0
        skipped earlier lines.  ``has_more`` still means only "more
        pages follow this one", so ``truncated`` is the single field to
        test for completeness.  ``estimated_tokens`` appears only with
        ``max_output_tokens`` and carries the token estimate of the
        untruncated output, alongside ``resource``, which names where
        the untruncated output can still be read.  Neither is a line of
        ``output``: the resource pointer used to be appended to the
        text, where it inflated ``shown`` past ``total_lines`` and cost
        a line of every page.
    """
    if timeout < 0:
        return json.dumps({"status": "error", "error": "timeout must be >= 0"})
    if max_output_tokens < 0:
        return json.dumps({"status": "error", "error": "max_output_tokens must be >= 0"})

    # --- Mode selection: commands (shell) vs argv (shell-free execve) ---
    # ``argv`` runs the program directly via ``exec_run`` without an
    # intervening ``/bin/bash -c``, so quoting / ``$'...'`` / embedded
    # newlines pass through literally (issue #234, #228 footgun).
    if argv is not None and commands:
        return json.dumps(
            {"status": "error", "error": "commands and argv are mutually exclusive"}
        )
    if argv is not None and not argv:
        return json.dumps(
            {"status": "error", "error": "argv must be a non-empty list"}
        )
    if argv is None and not commands:
        return json.dumps(
            {"status": "error", "error": "either commands or argv is required"}
        )

    use_argv = argv is not None
    if not use_argv and working_dir:
        assert commands is not None  # guaranteed by validation above
        commands = [f"cd {shlex.quote(working_dir)}"] + commands

    client = _docker()
    try:
        container = client.containers.get(container_id)
    except NotFound:
        return container_not_found_error(container_id)
    except Exception as e:
        return json.dumps({"status": "error", "error": str(e)})

    if argv is not None:
        journal_subject = list(argv)
    else:
        assert commands is not None  # guaranteed by validation above
        journal_subject = commands

    # Record the exec START before it runs (Issue #789).  A long-running
    # exec writes nothing to the journal while busy, so without this entry
    # the run would cross the dashboard's stall threshold mid-execution.
    # The completion entry below carries the real exit code; the start
    # entry (no exit_code) is the "call" for op counting in phase.py.
    journal_record_exec_start(
        container_id[:12],
        journal_subject,
        verbose=verbose,
    )

    # --- Foreground exec deadline (generalized #910 machinery) ---
    # Every synchronous sandbox_exec arms a server-owned wall-clock
    # deadline (SUNABA_FOREGROUND_TIMEOUT, default 270s) so a call that
    # outlives the MCP client's ~300s tool-call wait answers with a
    # terminal ``status: "timeout"`` result instead of leaving the
    # in-container command tree running and exhausting the container's PID
    # capacity.  The exec inherits the private per-call marker through the
    # environment; at expiry the watchdog reaps the whole marked tree
    # (TERM/KILL/probe) and the call returns the terminal timeout result.
    foreground_deadline_s = resolve_foreground_deadline()
    foreground_marker = new_foreground_marker()
    foreground_started_at = time.monotonic()
    try:
        # Armed inside the try so the finally always clears the thread-local
        # scope: tool calls run on a reused worker-thread pool, and a scope
        # left behind by a failed arm would leak into the next call.
        open_foreground_deadline(container, foreground_deadline_s, foreground_marker)

        # --- Execute ---
        if use_argv:
            assert argv is not None  # guaranteed by validation above
            # Direct execve: no /bin/sh, so the program receives argv
            # verbatim.  ``timeout(1)`` is prepended as argv (rather than a
            # shell wrapper) to preserve the timeout semantics.
            run_argv = ["timeout", str(timeout), *argv] if timeout > 0 else list(argv)
            exec_kwargs: dict[str, Any] = {"stdout": True, "stderr": True, "demux": True}
            if working_dir:
                exec_kwargs["workdir"] = working_dir
            marker_env = foreground_marker_environment()
            if marker_env is not None:
                exec_kwargs["environment"] = marker_env
            exit_code, output = run_exec_under_foreground_deadline(
                lambda: container.exec_run(run_argv, **exec_kwargs)
            )
        else:
            assert commands is not None  # guaranteed by validation above
            joined = " && ".join(commands)
            encoded = base64.b64encode(joined.encode("utf-8")).decode("ascii")
            tmpf = f"/tmp/.sx_{os.urandom(4).hex()}.sh"
            waitf = f"{tmpf}.wait"
            runner = f"timeout {timeout} {tmpf}" if timeout > 0 else tmpf
            # The wrapper runs under a child subreaper (see
            # shell.subreaper_exec_command) so a timed-out call's reap never
            # leaves orphaned zombies behind.
            rest = (
                f"echo {shlex.quote(encoded)} | base64 -d > {tmpf}"
                f" && chmod +x {tmpf}"
                f" && {runner}; rc=$?"
            )
            if timeout > 0:
                # Explicit-timeout path (decision 3): when ``timeout(1)``
                # fires (exit 124) the direct command is gone but ordinary
                # and setsid-detached descendants survive -- and, once their
                # ancestors die, they are reparented straight to PID 1 (the
                # sandbox images ship no init that reaps).  The wrapper
                # therefore sweeps the marked tree itself, while it is still
                # alive to reap the adopted orphans, before exiting with the
                # 124 contract.  The sweep runs with the marker removed from
                # its environment so it can never match its own processes.
                rest += (
                    f'; if [ "$rc" -eq 124 ]; then '
                    f"env -u {_FOREGROUND_MARKER_ENV} /bin/sh -c "
                    f"{shlex.quote(foreground_sweep_command(foreground_marker))}; fi"
                )
            # The wrapper must outlive the reaper's staged kill: it stays
            # alive (bounded) until every other marked process is gone, so
            # the descendants it adopted as the tree's subreaper are reaped
            # by it instead of falling to PID 1 as zombies.
            rest += foreground_wait_fragment(foreground_marker, waitf)
            rest += f"; rm -f {tmpf} {waitf}; exit $rc"
            cmd = subreaper_exec_command(rest)
            marker_env = foreground_marker_environment()
            exec_kwargs = {"stdout": True, "stderr": True, "demux": True}
            if marker_env is not None:
                exec_kwargs["environment"] = marker_env
            exit_code, output = run_exec_under_foreground_deadline(
                lambda: container.exec_run(["/bin/bash", "-c", cmd], **exec_kwargs)
            )
        stdout_part, stderr_part = output
        stdout_text = stdout_part.decode("utf-8", errors="replace") if stdout_part else ""
        stderr_text = stderr_part.decode("utf-8", errors="replace") if stderr_part else ""

        # Merge for output processing: success shows stdout only,
        # failure merges both so AI sees the full failure context
        if exit_code == 0:
            raw_output = stdout_text
        else:
            if stdout_text and stderr_text:
                raw_output = stdout_text + "\n" + stderr_text
            else:
                raw_output = stdout_text or stderr_text

        raw_size = len(raw_output.encode("utf-8"))
        clean = sanitize_output(raw_output)

        # Compress repeated lines
        compressed = compress_repeated_lines(clean)

        # Compress isomorphic failures
        if exit_code != 0:
            compressed = compress_failures(compressed)

        # Token-budget truncation (takes precedence over line-based).
        # ``total_lines`` stays a line count in both branches -- it used to
        # carry the token estimate here, which made the same key mean two
        # different units depending on max_output_tokens.  The token figure
        # keeps its own key instead.
        estimated_tokens: int | None = None
        if max_output_tokens > 0:
            display, original_tokens = truncate_by_tokens(compressed, max_output_tokens)
            total_lines = count_lines(compressed)
            estimated_tokens = original_tokens
            withheld = original_tokens > max_output_tokens
            # The pointer to the full output is an annotation about the
            # result, not a line of it.  Appending it to *display* made
            # shown count a line total_lines did not, and spent one slot
            # of the page, so output that fit in a single page could
            # still be reported as having more.
        else:
            display, meta = truncate_output(
                compressed,
                max_lines=max_lines,
                verbose=verbose,
                exit_code=exit_code,
                stderr=stderr_text,
            )
            total_lines = meta.total_lines
            # meta.truncated alone misses error_only's suppression of a
            # successful run's output, which withholds every line while
            # reporting no truncation.
            withheld = content_withheld(meta)

        envelope = build_output_envelope(
            display,
            total_lines=total_lines,
            content_withheld=withheld,
            offset=offset,
            limit=limit,
        )

        foreground_reap: str | None = None
        if exit_code == 0:
            status = "ok"
        elif timeout > 0 and exit_code == 124:
            status = "timeout"
            # The explicit ``timeout(N)`` fired: ``timeout(1)`` kills its
            # direct child only, so ordinary and setsid-detached
            # descendants may survive.  Reap the marked tree
            # deterministically before returning the terminal result.
            foreground_reap = reap_foreground_tree(container, foreground_marker)
        else:
            status = "error"

        result: dict[str, Any] = {
            "status": status,
            "output": envelope.output,
            "shown": envelope.shown,
            "total_lines": envelope.total_lines,
            "truncated": envelope.truncated,
            "next_offset": envelope.next_offset,
            "has_more": envelope.has_more,
        }
        if estimated_tokens is not None:
            result["estimated_tokens"] = estimated_tokens
        if exit_code != 0:
            result["exit_code"] = exit_code
        if stderr_text and verbose != "error_only":
            result["stderr"] = stderr_text
        if status == "timeout":
            assert foreground_reap is not None
            result["timeout"] = {
                "deadline_s": foreground_deadline_s,
                "reap": foreground_reap,
                "elapsed_s": time.monotonic() - foreground_started_at,
            }
    except ForegroundTreeTimeout as exc:
        # The server-side foreground deadline fired: the watchdog already
        # terminated and reaped the marked tree (or reported that it could
        # not).  Journal exactly one truthful terminal entry -- the timed-out
        # exec must never record a completion with exit code 0 -- and return
        # the terminal timeout result carrying the deadline diagnostics.
        journal_record_exec(
            container_id[:12],
            journal_subject,
            124,
            verbose=verbose,
        )
        return json.dumps({
            "status": "timeout",
            "exit_code": 124,
            "timeout": {
                "deadline_s": exc.deadline_s,
                "reap": exc.reap,
                "elapsed_s": exc.elapsed_s,
            },
        })
    except BaseException:
        # The START entry above must never be orphaned (#789 review):
        # without a closing record the run reads as in-flight until
        # the health grace window expires, and the call stays a
        # phantom in the op counters.  -2 is a synthetic exit code
        # meaning "exec aborted before completion"; any nonzero
        # value counts as a failure in phase.py.
        journal_record_exec(
            container_id[:12],
            journal_subject,
            -2,
            verbose=verbose,
        )
        raise
    finally:
        close_foreground_deadline()

    journal_record_exec(
        container_id[:12],
        journal_subject,
        exit_code,
        verbose=verbose,
        output_size=raw_size,
        max_output_tokens=max_output_tokens if max_output_tokens > 0 else None,
    )

    # Capture-health guard (issue #852): feed the decoded output and gate
    # the response.  A broken capture path returns a loud error instead of
    # a phantom ``status: ok`` + empty result.  Runs after the completion
    # journal record so the exec's real outcome stays journaled even when
    # the guard refuses to serve the result.
    guard_error = capture_health.check_capture(
        container,
        decoded_empty=not bool(stdout_text or stderr_text),
        container_id=container_id[:12],
    )
    if guard_error is not None:
        return guard_error

    if envelope.truncated or max_output_tokens > 0 or compressed != clean:
        output_id = OUTPUT_STORE.put(container_id, clean)
        if output_id is None:
            result["output_unavailable"] = "Full output exceeds the 8 MiB snapshot limit."
        else:
            result["output_id"] = output_id
            result["resource"] = "read_output(container_id, output_id, offset=0, limit=100)"

    return json.dumps(result)


def sandbox_exec_background(container_id: str, commands: Annotated[list[str], BeforeValidator(_coerce_list_arg)], working_dir: str = "") -> str:
    """Run commands with nohup in the repo root (/workspace);
    working_dir overrides it. Survives MCP disconnects.
    Returns a job ID for polling with sandbox_exec_check.

    Args:
        container_id: 12-character container ID prefix.
        commands: List of shell commands to execute sequentially.
        working_dir: Working directory to set before executing commands
            (default ``""`` = no change).

    Returns:
        Job ID string (container_id + timestamp + random hex) that can
        be used to poll execution status.

    Note:
        Multiple background jobs per container are fine: each job has
        its own result files in the container's ``/tmp`` keyed by its
        job_id, so concurrent jobs never overwrite one another.  The
        results survive server restarts but die with the container
        (``sandbox_stop`` / reaper), not with the server.
    """
    client = _docker()
    try:
        container = client.containers.get(container_id)
    except NotFound:
        return f"Error: container {container_id[:12]} not found"
    except Exception as e:
        return f"Error: {e}"

    if working_dir:
        commands = [f"cd {shlex.quote(working_dir)}"] + commands

    # The random hex suffix guarantees uniqueness even for two jobs
    # started in the same second on the same container (#829); without it
    # both jobs would share /tmp/{job_id}.start/.out/.err/.exit and the
    # two results would become indistinguishable.
    job_id = f"{container_id}-{int(time.time())}-{os.urandom(3).hex()}"
    joined = " && ".join(commands)
    encoded = base64.b64encode(joined.encode("utf-8")).decode("ascii")
    tmpf = f"/tmp/.sx_{os.urandom(4).hex()}.sh"
    inner_cmd = (
        f"echo {shlex.quote(encoded)} | base64 -d > {tmpf} && chmod +x {tmpf} && {tmpf}; rc=$?; rm -f {tmpf}; exit $rc"
    )
    # shlex.quote(job_id) is belt-and-braces: the id is generated here
    # from safe characters (container id/name + digits + hex), so the
    # quote is normally a no-op.
    qid = shlex.quote(job_id)
    bg_cmd = (
        f"date +%s > /tmp/{qid}.start && "
        f"nohup /bin/bash -c {shlex.quote(inner_cmd)} "
        f"> /tmp/{qid}.out 2> /tmp/{qid}.err; "
        f"echo $? > /tmp/{qid}.exit"
    )
    container.exec_run(
        ["/bin/bash", "-c", bg_cmd],
        detach=True,
        stdout=False,
        stderr=False,
    )

    # Record the dispatch in the audit journal.  The command runs detached
    # so its exit code is unknown at this point; -1 is a sentinel meaning
    # "background launch, outcome not yet known" (poll via sandbox_exec_check).
    # Without this, background execs were completely invisible to the
    # journal while foreground sandbox_exec records every call (Issue #359).
    journal_record_exec(
        container_id[:12],
        commands,
        -1,
        verbose="background",
    )
    return job_id


def sandbox_exec_check(container_id: str, job_id: str) -> str:
    """Poll a sandbox_exec_background job.
    Returns JSON status and timing, plus exit_code and output/error when done.

    Args:
        container_id: 12-character container ID prefix.
        job_id: Job ID returned by :func:`sandbox_exec_background`.

    Returns:
        JSON string with fields:

        * ``status``: ``"running"`` (job still in progress),
          ``"completed"`` (job finished), or ``"error"``
          (invalid job_id, container not found, or Docker API
          error; an invalid job_id is rejected before any Docker
          lookup, so it can be returned even for a live container).
        * ``elapsed_seconds``: seconds since the job started
          (``null`` if the ``.start`` file is unavailable, e.g.
          for jobs started before the timing feature was added).
        * ``last_output_seconds_ago``: seconds since stdout/stderr
          was last written (``null`` if no output files exist yet).
          Only present when ``status`` is ``"running"``.
        * ``exit_code``: integer exit code (only when ``status``
          is ``"completed"``).
        * ``output``: stdout text on success (only when
          ``status`` is ``"completed"`` and ``exit_code`` is 0).
        * ``error`` / ``stderr``: error details on failure.
    """
    # Validate job_id BEFORE any Docker call (#830).  A malformed id
    # (spaces, ";", newline, "$(...)") would otherwise be interpolated
    # into the /bin/sh -c string below and silently corrupt the
    # k, v = line.split("=", 1) parsing, flipping "running"/"completed"
    # instead of producing a clear error.  Both the current format
    # ("<container_id>-<seconds>-<hex>") and the pre-#829 format
    # ("<container_id>-<seconds>") are accepted so in-flight jobs started
    # before an upgrade stay checkable (see _JOB_ID_RE above).
    if not _JOB_ID_RE.fullmatch(job_id):
        return json.dumps({
            "status": "error",
            "error": (
                f"invalid job_id {job_id!r}: expected "
                "'<container_id>-<epoch>[-<hex>]'"
            ),
        })
    qid = shlex.quote(job_id)

    # Recovery/poll path: use a short Docker API timeout so a wedged or
    # unhealthy container fails fast instead of hanging the session
    # (Issue #181).
    client = _docker(timeout=RECOVERY_DOCKER_TIMEOUT)
    try:
        container = client.containers.get(container_id)
    except NotFound:
        return container_not_found_error(container_id)
    except Exception as e:
        return json.dumps({"status": "error", "error": str(e)})

    record_tool_use(container_id[:12], "sandbox_exec_check", {"job_id": job_id})

    # --- Single exec: gather timing, staleness, and exit status ---
    # job_id is shlex-quoted (qid) as belt-and-braces on top of the
    # validation above (#830).
    status_result = container.exec_run(
        [
            "/bin/sh", "-c",
            "echo NOW=$(date +%s); "
            f"echo START=$(cat /tmp/{qid}.start 2>/dev/null || echo ''); "
            f"echo OUT_MTIME=$(stat -c %Y /tmp/{qid}.out 2>/dev/null || echo 0); "
            f"echo ERR_MTIME=$(stat -c %Y /tmp/{qid}.err 2>/dev/null || echo 0); "
            f"echo EXIT=$(cat /tmp/{qid}.exit 2>/dev/null || echo 'not_found')",
        ],
        stdout=True, stderr=False,
    )
    status_output = status_result[1].decode("utf-8").strip()
    status_kv: dict[str, str] = {}
    for line in status_output.split("\n"):
        if "=" in line:
            k, v = line.split("=", 1)
            status_kv[k.strip()] = v.strip()

    # --- Parse now (safe) ---
    now = 0
    try:
        now = int(status_kv.get("NOW", "0"))
    except (ValueError, TypeError):
        pass

    # --- Elapsed: read .start file (available for jobs started after 2026-06) ---
    elapsed_seconds = None
    start_raw = status_kv.get("START", "")
    if start_raw:
        try:
            start_epoch = int(start_raw)
            elapsed_seconds = now - start_epoch
        except (ValueError, TypeError):
            pass

    # --- Staleness: time since last output write ---
    last_output_seconds_ago = None
    try:
        out_mtime = int(status_kv.get("OUT_MTIME", "0"))
        err_mtime = int(status_kv.get("ERR_MTIME", "0"))
        last_mtime = out_mtime if out_mtime > err_mtime else err_mtime
        if last_mtime > 0:
            last_output_seconds_ago = now - last_mtime
    except (ValueError, TypeError):
        pass

    # --- Check exit code file ---
    exit_code_output = status_kv.get("EXIT", "not_found")

    if exit_code_output == "not_found":
        # Capture-health guard (issue #870), one feed per client-facing
        # result.  The status command always echoes NOW=, START=, ...,
        # EXIT=, so a healthy capture is never empty here -- while a broken
        # one made every poll report ``status: running`` forever, the #852
        # fail-open shape.  Same per-container counter sandbox_exec feeds.
        guard_error = capture_health.check_capture(
            container,
            decoded_empty=not status_output,
            container_id=container_id[:12],
        )
        if guard_error is not None:
            return guard_error
        return json.dumps({
            "status": "running",
            "elapsed_seconds": elapsed_seconds,
            "last_output_seconds_ago": last_output_seconds_ago,
        })

    try:
        exit_code = int(exit_code_output) if exit_code_output else 0
    except (ValueError, TypeError):
        exit_code = -1

    # --- Read stdout ---
    stdout_result = container.exec_run(
        ["/bin/sh", "-c", f"cat /tmp/{qid}.out"],
        stdout=True, stderr=True,
    )
    stdout_text = stdout_result[1].decode("utf-8", errors="replace") if stdout_result[1] else ""

    # Capture-health guard (issue #870), one feed per client-facing
    # result: this call captured the status block and the job's stdout, so
    # "empty" means neither produced a byte.  A job that legitimately
    # printed nothing still has a non-empty status block, so it never
    # feeds an empty -- and when capture is broken both are empty and the
    # canary decides, exactly as for ``sandbox_exec(["true"])``.
    guard_error = capture_health.check_capture(
        container,
        decoded_empty=not (status_output or stdout_text),
        container_id=container_id[:12],
    )
    if guard_error is not None:
        return guard_error

    result: dict[str, Any] = {
        "status": "completed",
        "elapsed_seconds": elapsed_seconds,
        "exit_code": exit_code,
    }

    if exit_code != 0:
        stderr_result = container.exec_run(
            ["/bin/sh", "-c", f"cat /tmp/{qid}.err"],
            stdout=True, stderr=True,
        )
        stderr_text = stderr_result[1].decode("utf-8", errors="replace") if stderr_result[1] else ""
        result["error"] = f"exit code {exit_code}"
        if stderr_text:
            result["stderr"] = stderr_text
    else:
        result["output"] = stdout_text

    # --- Clean up temp files ---
    container.exec_run(
        [
            "/bin/sh",
            "-c",
            f"rm -f /tmp/{qid}.out /tmp/{qid}.err /tmp/{qid}.exit /tmp/{qid}.start",
        ],
        stdout=False,
        stderr=False,
    )

    return json.dumps(result)
